[package]
name = "askit-rig-agents"
version = "0.3.2"
description = "Rig Agents for Agent Stream Kit"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
agent-stream-kit = { version = "0.6", path = "../agent-stream-kit" }
rig-core = "0.19"
serde_json = "1"
